language: ruby
rvm:
- 1.9.3
- 2.0.0
- 2.1.0
- 2.1.1
env:
- DB=sqlite
- DB=mysql
- DB=postgresql
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rake
before_script:
- cp config/database.travis.yml config/database.yml
- mysql -e 'create database taskoholic_test'
- psql -c 'create database taskoholic_test' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: FqFQsHsu0cD3j/8ea9bNGD9TOtfC3hXEotDV91ow7ihyQEitUpknI+jj6etPDe6jJ5AseLUkFaEYDy4fbl8M5iFO7k65QHVkdj8eS2/epvoPeK4m60b0nNET3Yfusyy5lLiMnh8Lv5btR9zQZVStp5VFbs1rAzGPNCRwBYwYvKE=
  app:
    master: taskoholic
    dev: taskoholic-staging
  on:
    repo: RailsMafia/taskoholic
  run:
    - "rake db:create"
    - "rake db:migrate"